//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicsLabsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class devices_tb
    {
        public string device_name { get; set; }
        public decimal device_barcode { get; set; }
        public string lab_name { get; set; }
        public string device_status { get; set; }
        public string exp_name { get; set; }
        public int exp_num { get; set; }
        public string respon { get; set; }
        public string description { get; set; }
        public int ID { get; set; }
    }
}
